
package com.taekwondo.exporttomcat;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://exportTomcat.taekwondo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrounePersonnes", targetNamespace = "http://exportTomcat.taekwondo.com/", className = "com.taekwondo.exporttomcat.RetrounePersonnes")
    @ResponseWrapper(localName = "retrounePersonnesResponse", targetNamespace = "http://exportTomcat.taekwondo.com/", className = "com.taekwondo.exporttomcat.RetrounePersonnesResponse")
    public List<String> retrounePersonnes();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "ajoutePersonne", targetNamespace = "http://exportTomcat.taekwondo.com/", className = "com.taekwondo.exporttomcat.AjoutePersonne")
    @ResponseWrapper(localName = "ajoutePersonneResponse", targetNamespace = "http://exportTomcat.taekwondo.com/", className = "com.taekwondo.exporttomcat.AjoutePersonneResponse")
    public void ajoutePersonne(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcul", targetNamespace = "http://exportTomcat.taekwondo.com/", className = "com.taekwondo.exporttomcat.Calcul")
    @ResponseWrapper(localName = "calculResponse", targetNamespace = "http://exportTomcat.taekwondo.com/", className = "com.taekwondo.exporttomcat.CalculResponse")
    public int calcul(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://exportTomcat.taekwondo.com/", className = "com.taekwondo.exporttomcat.HelloWorld_Type")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://exportTomcat.taekwondo.com/", className = "com.taekwondo.exporttomcat.HelloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
